name: example
description: A new Flutter project to quickly test flutter_launcher_icons.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_launcher_icons:
    path: ../..

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/icon-710x599-android.png"
  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/images/icon-monochrome-432x432.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#FC5138"
  # Liquid Glass .icon configuration for iOS
  image_path_ios_liquid_glass_icon: "assets/images/icon-1024x1024.png"
  liquid_glass_icon_scale: 0.85
  liquid_glass_translucency_ios: 0.5
  liquid_glass_specular_ios: true
  liquid_glass_shadow_kind_ios: "Chromatic"
  liquid_glass_shadow_opacity_ios: 0.5
  liquid_glass_blur_ios: 0.5
  liquid_glass_offset_x_ios: 0.0
  liquid_glass_offset_y_ios: 0.0
  web:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
